version: '3.8'

services:
  sveltekit:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./sveltekit/.env
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    networks:
      - app_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./pocketbase/.env
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - app_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - pb_data:/pb/pb_data:rw
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # flarum:
  #   image: mondediefr/flarum:stable
  #   restart: unless-stopped
  #   env_file: ./flarum/.env
  #   depends_on:
  #     - flarum_db
  #   networks:
  #     - app_network

  # flarum_db:
  #   image: mariadb:10.6
  #   restart: unless-stopped
  #   env_file: ./flarum/db.env
  #   volumes:
  #     - /opt/app/flarum_db:/var/lib/mysql
  #   networks:
  #     - app_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - sveltekit
      - pocketbase
      # - flarum
    networks:
      - app_network

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    env_file: ./certbot/.env
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]
    command: sh -c 'certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email="$${CERTBOT_EMAIL}"
      -d thrivingindividuals.org
      -d www.thrivingindividuals.org
      --agree-tos 
      --non-interactive'

volumes:
  pb_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/pb_data
      o: bind
  # flarum_db_data:

networks:
  app_network:
    driver: bridge