name: Deploy Application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Create env files
        run: |
          # SvelteKit .env
          echo "${{ secrets.SVELTEKIT_ENV }}" > ./sveltekit/.env
          
          # Pocketbase .env
          echo "${{ secrets.POCKETBASE_ENV }}" > ./pocketbase/.env

          # Flarum .env
          # echo "${{ secrets.FLARUM_ENV }}" > ./flarum/.env
          # echo "${{ secrets.FLARUM_DB_ENV }}" > ./flarum/db.env

          # Certbot .env
          echo "${{ secrets.CERTBOT_ENV }}" > ./certbot/.env
      
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          source: "."
          target: "/opt/app"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/app
            chmod +x deploy.sh
            ./deploy.sh
