name: Deploy Application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create SSH directory
        run: mkdir -p ~/.ssh/
      
      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.VPS_HOST_KEY }}" >> ~/.ssh/known_hosts
      
      - name: Create env files
        run: |
          # SvelteKit .env
          echo "${{ secrets.SVELTEKIT_ENV }}" > ./sveltekit/.env
          
          # Pocketbase .env
          echo "${{ secrets.POCKETBASE_ENV }}" > ./pocketbase/.env

          # Flarum .env
          # echo "${{ secrets.FLARUM_ENV }}" > ./flarum/.env
          # echo "${{ secrets.FLARUM_DB_ENV }}" > ./flarum/db.env

          # Certbot .env
          echo "${{ secrets.CERTBOT_ENV }}" > ./certbot/.env
      
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/app"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/app
            chmod +x deploy.sh
            ./deploy.sh

      - name: Cleanup
        run: rm -rf ~/.ssh